### PR TITLE
Add technical details section to README.md

### PR DESCRIPTION
**Pull request by Sjord**
Add more information on what exactly semgrep-action does, and how differential
scanning works precisely. Describe which CI systems are supported. This makes
it easier to determine how this can be used outside of GitHub actions.

### CODE REVIEW

**Comment by Sjord** [comment]
@sabihb, @underyx ?

**Comment by dlukeomalley** [comment]
@Sjord Thank you for opening this PR! I have this queue up for review today 👀 

Would you prefer comments for you to address or for me to make any edits directly?

**Comment by Sjord** [comment]
Please feel free to edit directly.

**Comment by dlukeomalley** [comment]
Will do, thank you 🙏  I'm a little delayed, still on my queue and am rethinking where content should live between this repo and semgrep.dev/docs.

**Comment by underyx** [comment]
@dlukeomalley could you look at this this week?

**Review by ievans — APPROVED** [review]
Seems accurate to me, I haven't touched it super recently though. @dlukeomalley mind doing a review?

**Comment by chmccreery** [comment]
This is a great contribution, thank you @Sjord. I have created a new PR with these edits and a few minor adjustments, since the forking process seems to have borked our internal Semgrep tests. I am guessing it is because you don't have access to our API token. The new PR is at https://github.com/returntocorp/semgrep-action/pull/146 and since this was already approved, I am going to merge it now.

**Pull request closed without merging**
