### PR TITLE
Hack to reduce double run time

### PR DESCRIPTION
**Pull request by nbrahms**
BENTO_REGISTRY prevents caching, so copy the registry to a local file to
allow caching.

### CODE REVIEW

**Comment by nbrahms** [comment]
@underyx Do the test failures make sense to you?

**Comment by underyx** [comment]
> @underyx Do the test failures make sense to you?

Yep, that's a bug in develop. I'm pushing a fix now (along with type checking for `meta` there).

**Comment by nbrahms** [comment]
Should I rebase this PR then?

**Comment by underyx** [comment]
Yes please! CI is still failing due to an actual r2c rule though.

**Pull request merged**
