### PR TITLE
Ensuring --baseline-ref flag takes effect for GitHub/GitLab

### PR DESCRIPTION
**Pull request by karoun**
## What changed?

- See title; it stopped working for the `GITHUB_ACTIONS`/`GITLAB_CI` environment variables in #133 

## Test plan

CI

### CODE REVIEW

**Comment by ievans** [comment]
@cla-bot pls check. Thank so much for this @karoun!

**Comment by ievans** [comment]
Thank so much for this @karoun! @cla-bot check pls

**Review by underyx — APPROVED** [review]

**Comment by underyx** [comment]
Thanks so much! Just FYI I've added a commit changing our test snapshot normalization to remove all the blank debug lines (otherwise, adding debug calls anywhere would always change this snapshot for no clear reason.)

**Comment by underyx** [comment]
Thanks so much! Just FYI I've added a commit changing our test snapshot normalization to remove all the blank debug lines (otherwise, adding debug calls anywhere would always change this snapshot for no clear reason.)

**Comment by karoun** [comment]
Amazing, thanks for the super-speedy turnaround!

**Pull request merged**
