### PR TITLE
Build multiarch docker image

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by brendongo** [comment]
What is the intention here @sylr ?

**Review by MtMafia — APPROVED** [review]

**Comment by sylr** [comment]
Build docker images for those who run arm64 arch.

**Comment by brendongo** [comment]
Is there an easy way to test this locally?

**Comment by sylr** [comment]
```
docker buildx build . -t semgrep:dev --platform=linux/amd64,linux/arm64
```

**Comment by brendongo** [comment]
Closing since we don't have a good way to test the built images and haven't decided to support the other architectures in docker

**Pull request closed without merging**
